// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicioGrpcJWT.Data;

namespace ServicioGrpcJWT.Migrations
{
    [DbContext(typeof(JWTContext))]
    [Migration("20220928182830_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServicioGrpcJWT.Entidades.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Habitantes")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pais");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f240a38f-cf29-40a8-b94a-c5ee4863dbd0"),
                            Habitantes = 46000000,
                            Nombre = "España"
                        },
                        new
                        {
                            Id = new Guid("a551dc1e-8edb-454d-baed-45f710eb2033"),
                            Habitantes = 83000000,
                            Nombre = "Alemania"
                        },
                        new
                        {
                            Id = new Guid("6c26bb60-b483-41cb-af1d-fc6cb5bc040d"),
                            Habitantes = 65000000,
                            Nombre = "Francia"
                        },
                        new
                        {
                            Id = new Guid("90e98eb4-739b-44cc-a5be-c30d559950b2"),
                            Habitantes = 61000000,
                            Nombre = "Italia"
                        },
                        new
                        {
                            Id = new Guid("e8d28795-04c1-461c-bdb8-e2d56652e6d6"),
                            Habitantes = 96000000,
                            Nombre = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("b086db89-a75b-40d2-b6ce-a9b7bff26d4f"),
                            Habitantes = 63000000,
                            Nombre = "EUA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
